apiVersion: v1
kind: ConfigMap
metadata:
  name: scanflow-server-env
  namespace: {{ .Release.Namespace }}
data:
  SCANFLOW_TRACKER_URI: http://{{ .Release.Name }}-tracker-service.{{ .Release.Namespace }}.svc.cluster.local