apiVersion: v1
kind: ConfigMap
metadata:
  name: scanflow-tracker-env
  namespace: {{ .Release.Namespace }}
data:
  TRACKER_STORAGE: {{.Values.tracker.scanflow_tracker_storage_backend}}://{{.Values.tracker.scanflow_tracker_storage_username}}:{{.Values.tracker.scanflow_tracker_storage_password}}@{{.Values.tracker.scanflow_tracker_storage_url}}/scanflow
  TRACKER_ARTIFACT: {{.Values.tracker.scanflow_tracker_artifact_backend}}://scanflow