apiVersion: v1
kind: Secret
metadata:
  name: scanflow-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{.Values.tracker.scanflow_tracker_artifact_username}}
  AWS_SECRET_ACCESS_KEY: {{.Values.tracker.scanflow_tracker_artifact_password}}
  MLFLOW_S3_ENDPOINT_URL: {{.Values.tracker.scanflow_tracker_artifact_url}}
