#for developing server, I mount the current path to the server container, but this can be remove later once scanflow is stable.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scanflow-server
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  claimRef:
    namespace: scanflow-server
    name: pvc-scanflow-server
  hostPath:
    path: "/home/rocky/k8s_resources"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scanflow-server
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi 

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: scanflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanflow-server
  template:
    metadata:
      labels:
        app: scanflow-server
    spec:
      nodeName: cloudskin-k8s-control-plane-0.novalocal
      volumes:
        - name: pvc-scanflow-server
          persistentVolumeClaim:
            claimName: pvc-scanflow-server
      containers:
          - name: {{ .Release.Name }}-server
            image: {{.Values.basic.scanflow_server_image_name}}:{{.Values.basic.image_tag_version}}
            imagePullPolicy: Always
            #temp
            #command: ["/bin/sh"]
            #args: ["-c", "pip install --pre --upgrade kubernetes && uvicorn server:app --reload --host 0.0.0.0 --port 8080"]

            #env:
            #  - name: SCANFLOW_TRACKER_URI
            #    value: http://{{ .Release.Name }}-tracker-service.{{ .Release.Namespace }}.svc.cluster.local
            #  - name: MLFLOW_S3_ENDPOINT_URL
            #    value: {{.Values.tracker.scanflow_tracker_artifact_url}}
            #  - name: AWS_ACCESS_KEY_ID
            #    value: {{.Values.tracker.scanflow_tracker_artifact_username}}
            #  - name: AWS_SECRET_ACCESS_KEY
            #    value: {{.Values.tracker.scanflow_tracker_artifact_password}}
            envFrom:
              - secretRef:
                  name: scanflow-secret
              - configMapRef:
                  name: scanflow-server-env
            volumeMounts:
              - mountPath: /scanflow
                name: pvc-scanflow-server
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-service
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32767
  selector:
    app: scanflow-server
  type: NodePort