apiVersion: v1
kind: Pod
metadata:
  name: mlperf-pod
  namespace: scanflow-ai-pa
  labels:
    app: mlperf-pod
spec:
  nodeName: nxt2027 
  containers:
  - name: mlperf-pod
    image: 172.30.0.49:5000/mlperf:latest
    imagePullPolicy: Always
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]

