
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

ENV AGENT_BASE_PATH  /planner
ENV AGENT_HOME  /planner/agent
ENV AGENT_PORT  8007

RUN pip install mlflow==1.14.1
RUN pip install fastapi
RUN pip install uvicorn
RUN pip install aiohttp
RUN pip install aiodns

RUN mkdir $AGENT_BASE_PATH
RUN mkdir -p $AGENT_HOME

WORKDIR $AGENT_HOME

CMD uvicorn planner_agent:app --reload --host 0.0.0.0 --port $AGENT_PORT

