apiVersion: v1
kind: Pod
metadata:
  name: mlperf-pod
  namespace: scanflow-mlperf-dataengineer
  labels:
    app: mlperf-pod
spec: 
  containers:
  - name: mlperf-pod
    image: 172.30.0.49:5000/mlperf:latest
    imagePullPolicy: Always
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]

