
FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-agent

ENV AGENT_NAME checker
ENV AGENT_TYPE analyzer

RUN mkdir /agent
COPY checker /agent

ENV sensors '{"count_number_of_newdata": {"name": "count_number_of_newdata", "func": "scanflow.agent.template.analyzer.custom_sensors.count_number_of_newdata", "trigger": {"type": "interval", "weeks": 0, "days": 0, "hours": 1, "minutes": 0, "seconds": 0, "start_date": null, "end_date": null, "timezone": null, "jitter": null}}}' 

CMD [ "cp /agent/* /scanflow/scanflow/scanflow/agent/template/analyzer && uvicorn main:agent --reload --host 0.0.0.0 --port 8080" ]
