

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/modeling-cnn1:latest

COPY modeling-cnn2 /app/modeling-cnn2

RUN pip install -r /app/modeling-cnn2/req_modeling.txt

ENTRYPOINT ["python", "/app/modeling-cnn2/modeling.py"]
