
FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-agent

ENV AGENT_NAME tracker
ENV AGENT_TYPE monitor

RUN mkdir /agent
COPY tracker /agent

ENV sensors '{"count_number_of_predictions": {"name": "count_number_of_predictions", "func": "scanflow.agent.template.monitor.custom_sensors.count_number_of_predictions", "trigger": {"type": "interval", "weeks": 0, "days": 0, "hours": 1, "minutes": 0, "seconds": 0, "start_date": null, "end_date": null, "timezone": null, "jitter": null}}}' 

CMD [ "cp /agent/* /scanflow/scanflow/scanflow/agent/template/monitor && uvicorn main:agent --reload --host 0.0.0.0 --port 8080" ]
