
FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-agent

ENV AGENT_NAME planner
ENV AGENT_TYPE planner

RUN mkdir /agent
COPY planner /agent

ENV sensors '{"check_model_accuracy": {"name": "check_model_accuracy", "func": "scanflow.agent.template.planner.custom_sensors.check_model_accuracy", "trigger": {"type": "interval", "weeks": 0, "days": 0, "hours": 1, "minutes": 0, "seconds": 0, "start_date": null, "end_date": null, "timezone": null, "jitter": null}}}' 

CMD [ "cp /agent/* /scanflow/scanflow/scanflow/agent/template/planner && uvicorn main:agent --reload --host 0.0.0.0 --port 8080" ]
