

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/modeling-cnn1:latest

COPY predictor-batch /app/predictor-batch

ENTRYPOINT ["python", "/app/predictor-batch/predictor.py"]
