

FROM python:3.7-slim 

COPY postprocessing-online /app
WORKDIR /app
EXPOSE 5000

RUN pip install -r /app/requirements.txt

ENV MODEL_NAME upload
ENV SERVICE_TYPE MODEL

CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE
