

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-executor

COPY modeling-cnn1 /app/modeling-cnn1

RUN pip install -r /app/modeling-cnn1/req_modeling.txt

ENTRYPOINT ["python", "/app/modeling-cnn1/modeling.py"]
