

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/checker:latest

COPY detector-batch /app/detector-batch

ENTRYPOINT ["python", "/app/detector-batch/checker.py"]
