{
 "title": "ScanflowPanel",
 "description": "for scanflow plaftform",
 "tags": [ "Scanflow" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values(kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}, created_by_name)"
    }
   },
   {
    "name": "PodbyJob",
    "query": {
     "query": "label_values(kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\", created_by_name=\"$Job\"}, pod)"
    }
   },
   {
    "name": "PodbyNode",
    "query": {
     "query": "label_values(kube_pod_info{kubernetes_namespace=\"volcano-monitoring\", node=\"$Node\"}, pod)"
    }
   },
   {
    "name": "RunningPodbyNode",
    "query": {
     "query": "query_result(kube_pod_container_status_running{kubernetes_namespace=\"volcano-monitoring\", pod=~\"$PodbyNode\"}==1)"
    }
   },
   {
    "name": "TerminatedPodbyNode",
    "query": {
     "query": "query_result(kube_pod_container_status_terminated{kubernetes_namespace=\"volcano-monitoring\", pod=~\"$PodbyNode\"}==1)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{kubernetes_namespace=\"volcano-monitoring\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node dashboard(node resource requests)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node cpu requests %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (sum(kube_pod_container_resource_requests_cpu_cores{kubernetes_namespace=\"volcano-monitoring\"}) by (namespace, pod, node) * on (namespace, pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",kubernetes_namespace=\"volcano-monitoring\"}) by (pod, namespace) == 1)) / sum by (node) (kube_node_status_allocatable_cpu_cores{kubernetes_namespace=\"volcano-monitoring\"}) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory requests %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (sum(kube_pod_container_resource_requests_memory_bytes{kubernetes_namespace=\"volcano-monitoring\"}) by (namespace, pod, node) * on (namespace, pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",kubernetes_namespace=\"volcano-monitoring\"}) by (pod, namespace) == 1)) / sum by (node) (kube_node_status_allocatable_memory_bytes{kubernetes_namespace=\"volcano-monitoring\"}) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node dashboard(node resource usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node cpu usage %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum by (kubernetes_io_hostname) (label_replace(kube_node_status_allocatable_cpu_cores{kubernetes_namespace=\"volcano-monitoring\"}, \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\")) * 100 ",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "Node memory usage %",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_io_hostname) (rate(container_memory_working_set_bytes{id=\"/\"}[1m])) / sum by (kubernetes_io_hostname) (label_replace(kube_node_status_allocatable_memory_bytes{kubernetes_namespace=\"volcano-monitoring\"}, \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\")) * 100",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "title": "Node network bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum by (kubernetes_io_hostname) (rate(container_network_receive_bytes_total{id=\"/\"}[1m])) + sum by (kubernetes_io_hostname) (rate(container_network_transmit_bytes_total{id=\"/\"}[1m]))) ",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node export(node resource usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node cpu usage (sys,user,iowait...)%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance) (avg without(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node cpu usage (idle)%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (instance) (avg without(cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node memory usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (instance) (node_memory_MemTotal_bytes) - sum by (instance) (node_memory_MemAvailable_bytes))/(sum by (instance) (node_memory_MemTotal_bytes)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node network bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_network_receive_bytes_total[1m])) + sum by (instance) (rate(node_network_transmit_bytes_total[1m]))) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node network bandwidth - infiniband",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum by (instance) (rate(node_infiniband_port_data_received_bytes_total[1m])) + sum by (instance) (rate(node_infiniband_port_data_transmitted_bytes_total[1m]))) ",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Job dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Job(pods) cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (created_by_name) (sum (rate (container_cpu_usage_seconds_total{id!=\"/\", container=\"\"}[1m])) by (namespace, pod) * on (namespace, pod) group_right() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace, created_by_name)))",
     "legendFormat": " {{created_by_name}}"
    }
   ]
  },
  {
   "title": "Job(pods) memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (created_by_name) (sum (container_memory_working_set_bytes{id!=\"/\", container=\"\"}) by (namespace, pod) * on (namespace, pod) group_right() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace, created_by_name))) ",
     "legendFormat": " {{created_by_name}}"
    }
   ]
  },
  {
   "title": "Job(pods) network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (created_by_name) (sum (rate(container_network_receive_bytes_total{id!=\"/\"}[1m])) by (namespace, pod) * on (namespace, pod) group_right() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace, created_by_name))) ",
     "legendFormat": " {{created_by_name}}"
    }
   ]
  },
  {
   "title": "Job(pods) per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (node) (sum(kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (namespace, pod, node) * on (namespace, pod) group_left() (sum(kube_pod_status_phase{phase=\"Running\",kubernetes_namespace=\"volcano-monitoring\"}) by (pod, namespace) == 1))",
     "legendFormat": " {{node}}"
    }
   ]
  },
  {
   "title": "Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (created_by_name) (sum (kube_pod_status_phase{phase=\"Pending\",kubernetes_namespace=\"volcano-monitoring\"}) by (namespace, pod) * on (namespace, pod) group_right() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace, created_by_name)))",
       "legendFormat": "{{ create_by_name }}"
      }
     ]
    },
    {
     "title": "Running Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "expr": "sum by (created_by_name) (sum (kube_pod_status_phase{phase=\"Running\",kubernetes_namespace=\"volcano-monitoring\"}) by (namespace, pod) * on (namespace, pod) group_right() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace, created_by_name)))",
       "legendFormat": "{{ create_by_name }}"
      }
     ]
    },
    {
     "title": "Succeeded Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "targets": [
      {
       "expr": "sum by (created_by_name) (sum (kube_pod_status_phase{phase=\"Succeeded\",kubernetes_namespace=\"volcano-monitoring\"}) by (namespace, pod) * on (namespace, pod) group_right() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace, created_by_name)))",
       "legendFormat": "{{ create_by_name }}"
      }
     ]
    },
    {
     "title": "Workloads status",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (phase) (sum (kube_pod_status_phase{kubernetes_namespace=\"volcano-monitoring\"}) by (namespace, pod, phase) * on (namespace, pod) group_left() (group (kube_pod_info{kubernetes_namespace=\"volcano-monitoring\",created_by_kind=\"Job\"}) by (pod, namespace)))",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  }
 ]
}