

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-executor

COPY checker /app/checker

RUN pip install -r /app/checker/req_checker.txt

ENTRYPOINT ["python", "/app/checker/checker.py"]
